spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: Dalin@1998$$
        initialization-mode: always
        
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis_config.xml
# --- server
server:
  port: 8282
  error:
    include-message: always
  

    
logging:
  level: 
    com.core.authorization.repository: debug

